version: '3.3'

services:
  webserver:
    build: .
    ports:
      - "8888:80"

    links:
      - mysql:mysql

    restart: always

    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: mypass
      MYSQL_USER: lee
      MYSQL_PASSWORD: leepass
      MYSQL_DATABASE: leedb

    volumes:
      - dbdata:/var/lib/mysql

    ports:
      - "3306:3306"

volumes:
  dbdata: {}
